import { buildVehicleHistoryDocDefinition, type VehicleHistoryPdfInput } from '@/lib/pdfBuildHistory'

/**
 * The builder is pure: the route resolves the wording and passes it in,
 * so a test supplies its own. Distinctive values, so an assertion that a
 * label reached the document cannot pass by coincidence.
 */
const STRINGS: VehicleHistoryPdfInput['strings'] = {
  subtitle: 'Off-road build log',
  generation: 'Generation',
  engine: 'Engine',
  vin: 'VIN',
  progressLabel: 'Built',
  totalSpentLabel: 'Total spent',
  jobsLoggedLabel: 'Jobs logged',
  periodLabel: 'Period',
  expenses: 'Expenses',
  byCategory: 'BY CATEGORY',
  everyExpense: 'EVERY EXPENSE',
  colDate: 'DATE',
  colItem: 'JOB',
  colCategory: 'CATEGORY',
  colType: 'TYPE',
  colAmount: 'AMOUNT',
  total: 'Total',
  noExpenses: 'No expenses recorded yet.',
  foundState: 'Found state',
  acquired: 'Acquired',
  purchasePrice: 'Purchase price',
  odometer: 'Odometer',
  condition: 'Condition',
  workshop: 'Workshop',
  diy: 'DIY',
  generatedOn: 'Generated by RigLog on 01.05.2024',
}

/** A task with everything set, so a case only states what it varies. */
const BASE_TASK: VehicleHistoryPdfInput['categories'][number]['tasks'][number] = {
  name: 'A job',
  brand: null,
  statusLabel: 'Done',
  workType: 'DIY',
  date: new Date('2024-01-01'),
  totalCost: 100,
  workshopName: null,
  notes: null,
  photos: [],
}

const BASE_INPUT: VehicleHistoryPdfInput = {
  strings: STRINGS,
  vehicleName: '2001 Jeep Wrangler',
  projectType: 'OFFROAD',
  generation: 'TJ',
  engine: '4.0L I6',
  vin: '1J4FA49S31P123456',
  coverPhotoDataUri: null,
  progressLabel: 'Build progress',
  progressPct: 42,
  totalSpent: 12500,
  categories: [
    {
      categoryLabel: 'Suspension',
      tasks: [
        {
          name: 'Lift kit',
          brand: 'Rubicon Express',
          statusLabel: 'Done',
          workType: 'DIY',
          date: new Date('2024-03-01'),
          totalCost: 3500,
          workshopName: null,
          notes: null,
          photos: [],
        },
      ],
    },
  ],
  foundState: null,
  generatedAt: new Date('2024-06-01'),
}

describe('buildVehicleHistoryDocDefinition', () => {
  it('includes the vehicle name and the headline figures', () => {
    const doc = buildVehicleHistoryDocDefinition(BASE_INPUT)
    const content = JSON.stringify(doc.content)
    // Not by index: the document opens with a masthead now, and an
    // assertion pinned to content[0] only tested the running order.
    expect(content).toContain('2001 Jeep Wrangler')
    expect(content).toContain('Total spent')
    expect(content).toContain('Jobs logged')
  })

  it('omits the found state section for an off-road vehicle', () => {
    const doc = buildVehicleHistoryDocDefinition(BASE_INPUT)
    const content = JSON.stringify(doc.content)
    expect(content).not.toContain('Found state')
  })

  it('includes a found state section for a restoration vehicle when populated', () => {
    const doc = buildVehicleHistoryDocDefinition({
      ...BASE_INPUT,
      projectType: 'RESTORATION',
      foundState: {
        acquisitionDate: new Date('2020-01-01'),
        purchasePriceRon: 15000,
        odometer: 120000,
        knownHistory: 'Barn find, one owner.',
        conditionRating: 3,
        photos: [],
      },
    })
    const content = JSON.stringify(doc.content)
    expect(content).toContain('Found state')
    expect(content).toContain('Barn find, one owner.')
  })

  it('skips categories with no tasks', () => {
    const doc = buildVehicleHistoryDocDefinition({
      ...BASE_INPUT,
      categories: [
        { categoryLabel: 'Suspension', tasks: BASE_INPUT.categories[0].tasks },
        { categoryLabel: 'Empty category', tasks: [] },
      ],
    })
    const content = JSON.stringify(doc.content)
    expect(content).not.toContain('Empty category')
  })

  it('renders task cost formatted as RON', () => {
    const doc = buildVehicleHistoryDocDefinition(BASE_INPUT)
    const content = JSON.stringify(doc.content)
    expect(content).toContain('3.500,00 RON')
  })

  it('embeds up to the photos passed in as image nodes', () => {
    const doc = buildVehicleHistoryDocDefinition({
      ...BASE_INPUT,
      categories: [
        {
          categoryLabel: 'Suspension',
          tasks: [
            {
              ...BASE_INPUT.categories[0].tasks[0],
              photos: [{ dataUri: 'data:image/jpeg;base64,AAA', caption: null }],
            },
          ],
        },
      ],
    })
    const content = JSON.stringify(doc.content)
    expect(content).toContain('data:image/jpeg;base64,AAA')
  })

  it('provides a footer function that renders page numbers', () => {
    const doc = buildVehicleHistoryDocDefinition(BASE_INPUT)
    expect(typeof doc.footer).toBe('function')
    const footer = doc.footer as (p: number, c: number) => unknown
    expect(JSON.stringify(footer(2, 5))).toContain('2 / 5')
  })
})

/**
 * The expense report: every cost, with its date, as a ledger.
 *
 * The build sections above group the same jobs by category, which answers
 * "what has been done to this car". This answers "what has it cost and
 * when", which is the question you print it for — to settle up with a
 * collaborator, or to hand over with the vehicle.
 */
describe('the expense report', () => {
  const INPUT: VehicleHistoryPdfInput = {
    ...BASE_INPUT,
    categories: [
      {
        categoryLabel: 'Recovery',
        tasks: [
          { ...BASE_TASK, name: 'Winch', date: new Date('2024-05-02'), totalCost: 3500, workType: 'DIY' },
          { ...BASE_TASK, name: 'Recovery points', date: new Date('2024-01-10'), totalCost: 600, workType: 'WORKSHOP' },
        ],
      },
      {
        categoryLabel: 'Suspension',
        tasks: [{ ...BASE_TASK, name: 'Lift kit', date: new Date('2024-03-15'), totalCost: 4200, workType: 'DIY' }],
      },
    ],
  }

  const render = (input: VehicleHistoryPdfInput) => JSON.stringify(buildVehicleHistoryDocDefinition(input).content)

  it('lists every expense with its date', () => {
    const content = render(INPUT)
    for (const [name, date] of [['Winch', '02.05.2024'], ['Recovery points', '10.01.2024'], ['Lift kit', '15.03.2024']]) {
      expect(content).toContain(name)
      expect(content).toContain(date)
    }
  })

  it('runs oldest first, whatever order the categories came in', () => {
    // Searched from the ledger onwards: the period stat tile at the top
    // names the first and last dates, so a search over the whole document
    // finds 02.05.2024 before 15.03.2024 for reasons that have nothing to
    // do with the table's order.
    const content = render(INPUT)
    const ledger = content.slice(content.indexOf('EVERY EXPENSE'))
    // A ledger runs forwards. The categories above deliberately hold their
    // tasks out of order so this cannot pass by accident.
    const positions = ['10.01.2024', '15.03.2024', '02.05.2024'].map((d) => ledger.indexOf(d))
    expect(positions).toEqual([...positions].sort((a, b) => a - b))
    expect(positions.every((p) => p > -1)).toBe(true)
  })

  it('totals the expenses', () => {
    expect(render(INPUT)).toContain('8.300,00 RON')
  })

  it('subtotals by category', () => {
    const content = render(INPUT)
    expect(content).toContain('4.100,00 RON') // Recovery: 3500 + 600
    expect(content).toContain('4.200,00 RON') // Suspension
  })

  it('says which jobs were workshop and which were DIY', () => {
    const content = render(INPUT)
    expect(content).toContain('Workshop')
    expect(content).toContain('DIY')
  })

  it('says so rather than printing an empty table when there is nothing to report', () => {
    const content = render({ ...INPUT, categories: [] })
    expect(content).toContain('No expenses recorded yet.')
  })

  it('reports the period the expenses span', () => {
    expect(render(INPUT)).toContain('10.01.2024 – 02.05.2024')
  })

  it('does not print a progress bar for a daily driver', () => {
    // tracksCompletion is false for that mode — a repair log accumulates
    // rather than working towards a finished state, so a percentage of it
    // would mean nothing.
    const doc = buildVehicleHistoryDocDefinition({ ...INPUT, projectType: 'DAILY_DRIVER', progressPct: 0 })
    const bars = JSON.stringify(doc.content).match(/"type":"rect"/g) ?? []
    const withBar = buildVehicleHistoryDocDefinition({ ...INPUT, projectType: 'OFFROAD' })
    const barsWithProgress = JSON.stringify(withBar.content).match(/"type":"rect"/g) ?? []
    expect(barsWithProgress.length).toBeGreaterThan(bars.length)
  })
})
